name: 数据库 Check

on:
  push:
    paths:
      - '数据库/**'
  pull_request:
    paths:
      - '数据库/**'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './数据库'
