name: 面板工具 Check

on:
  push:
    paths:
      - '面板工具/**'
  pull_request:
    paths:
      - '面板工具/**'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './面板工具'
